#+SETUPFILE: setup.org
#+TITLE: The Turing test

* The imitation game

The game is played by three people: a man (/A/), a woman (/B/), and an
interrogator (/C/) who may be of either sex. The interrogator stays in
a separate room. The object of the game is for the interrogator to
determine who of /A/ and /B/ (known to the interrogator as /X/ and
/Y/) is the man and who is the woman.

The interrogator asks questions of /A/ and /B/ such as: Will /X/
please tell me the length of his or her hair?

/A/ wants /C/ (the interrogator) to come to the wrong
conclusion. Thus, /A/ may say his hair is long (which, we are
supposing, gives /C/ reason to think that /A/ is a woman, i.e. that
/A/ is /B/).

Clearly, some measures must be taken so that /C/ cannot simply see or
hear who is the man and who is the woman. So conversation happens
through a typewriter.

/B/, unlike /A/, wants /C/ to come to the right conclusion. So, /B/
may say, "I am the woman!" But so might /A/.

** What's happening?

Before we talk about replacing one of these players with a machine, we
should try to understand what Turing is doing here. Let's take it for
granted (as I suppose he did) that men and women are quite different;
that there is some /fundamental/ distinction and a sophisticated
interrogator might have a chance of telling them apart. (This must be
Turing's belief because the imitation game is pointless if there is no
reasonable way to distinguish the players, for example distinguishing
identical twins with similar life experiences, neither of whom you
know closely.)

So, given that men and women are very different, person /A/ would
succeed in confusing the interrogator (making /C/ believe that /X/ is
/B/ rather than the true answer, /A/), and similarly, person /B/ would
fail in convincing /C/ of the truth, if /A/ is a better imitator of a
woman than /B/ is, and furthermore that /B/'s arguments to the
contrary fail.

Thus, /B/ may win (expose /A/ as a man) if /A/ is a bad imitator or
/B/ has really strong arguments.

Suppose /C/ gets the right answer only p% of the time (perhaps with
different interrogators but the same /A/ and /B/ players; Turing is
unclear here). This performance p% is important to keep in mind.

** Replace the man with a machine!

Now we are ready to understand why Turing set up this game to test
machine intelligence. If we replace /A/ with a machine (perhaps /B/ is
still a woman, perhaps not, but of course is a human), then we have a
test for machine intelligence.

Now, the machine is trying to convince the interrogator that it is a
human, but the human is not. The human is trying to convince the
interrogator that he or she is a human, but the machine is not.

Just as, supposedly, a man would find it difficult to immitate a
woman, a machine would probably find it difficult to immitate a
human. Yet, if the machine is not only able to act like a human but
also (or alternatively?) to counteract the arguments produced by the
human, then the machine is quite intelligent indeed.

Some interrogator may be naive. Thus, I believe this performance p%
is relevant. If the same machine and human players (or perhaps
different human players) can convince different interrogators more
often than /p/% of the time, then the machine has passed the test. The
machine need not achieve perfect performance (p = 100%), just has to
beat human performance. (Because, presumably, humans are the most
intelligent creatures that can be used in this test.)

I don't believe there is any reason to suppose a man can successfully
convince a judge he is a woman and the woman is a man more than 50% of
the time. If a man could do this, then he acts like a woman better
than most other women, and furthermore can counteract their arguments
to the contrary. Because the woman is arguing as well, maximum
performance near 25% is probably more appropriate. Anyway, the
machine's goal is to beat that figure, not achieve perfect
convincing. The existence of a machine that can consistently convince
a judge that it is human and the human is a machine, even though the
human is begging for mercy, is an amazing thought!

** We have a long way to go

Nobody actually practices with a real Turing test. It's too hard for
the machine. Instead, the yearly [[http://www.loebner.net/Prizef/loebner-prize.html][Loebner Prize]] experiments with a
reduced form of this test. The judges simply estimate how "closely" a
computer imitates a human, and judges are not allowed to attempt
trickery (such as typing random symbols) or delve into deep
conversation.

* Podcasts

** Talking to machines (Radiolab, May 31, 2011)

#+BEGIN_CENTER
#+BEGIN_HTML
<embed
flashvars="file=http://www.radiolab.org/audio/xspf/137407/&repeat=list&autostart=false&popurl=http://www.radiolab.org/audio/xspf/137407/%3Fdownload%3Dhttp%3A//www.podtrac.com/pts/redirect.mp3/audio.wnyc.org/radiolab/radiolab053111.mp3"
quality="high" allowscriptaccess="always" wmode="transparent"
src="http://www.radiolab.org/media/audioplayer/player5.swf"
height="300" width="400"></embed><script
type="text/javascript">(function(){var
s=function(){__flash__removeCallback=function(i,n){if(i)i[n]=null;};window.setTimeout(s,10);};s();})();</script>
#+END_HTML

1 hour / [[http://www.podtrac.com/pts/redirect.mp3/audio.wnyc.org/radiolab/radiolab053111.mp3][Download MP3]] / [[http://www.radiolab.org/2011/may/31/][Radiolab website for this episode]]

#+END_CENTER

** The Turing Problem (Radiolab, March 19, 2012)

#+BEGIN_CENTER
#+BEGIN_HTML
<embed
flashvars="file=http://www.radiolab.org/audio/xspf/193037/&repeat=list&autostart=false&popurl=http://www.radiolab.org/audio/xspf/193037/%3Fdownload%3Dhttp%3A//www.podtrac.com/pts/redirect.mp3/audio.wnyc.org/radiolab_podcast/radiolab_podcast12turing.mp3"
quality="high" allowscriptaccess="always" wmode="transparent"
src="http://www.radiolab.org/media/audioplayer/player5.swf"
height="300" width="400"></embed><script
type="text/javascript">(function(){var
s=function(){__flash__removeCallback=function(i,n){if(i)i[n]=null;};window.setTimeout(s,10);};s();})();</script>
#+END_HTML

23 minutes / [[http://www.podtrac.com/pts/redirect.mp3/audio.wnyc.org/radiolab_podcast/radiolab_podcast12turing.mp3][Download MP3]] / [[http://www.radiolab.org/blogs/radiolab-blog/2012/mar/19/turing-problem/][Radiolab website for this episode]]

#+END_CENTER

#+INCLUDE: footer.org

